# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcf30a3334bc7063fe5e5b077294c78f1a6181915a31c5d28afd02197380557cd53da0587e8f1799a8aa63180c4bd19358fc8a98c0a46a87c3bfb0fe634b7030

test:
  secret_key_base: eca8482bb246c8dfeae868e27097c813953c0d648ab1d5863cb92acdcc2c6566d8a69c0adfe2ecda64c47cbcf7bb7d78c6aecdcc3e581528f1d1ea9480a2e9ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
